### ISSUE TITLE
Generate release

### ISSUE THREAD

**Issue by vcampitelli** [baxast/astro-compress#1]
Hey there!

I don't know what happened to the repo, but thanks @NikolaRHristov for getting it back.

Can you please run the NPM workflow to publish it to the registry, please? [The current version there is empty](https://www.npmjs.com/package/astro-compress?activeTab=code).

**Comment by NikolaRHristov** [comment]
Hello, @vcampitelli, it's not just about generating a release and releasing it into the the public. I have to make sure that the thing works, flawlessly, otherwise thousands of websites will be down. It's easy for you to just say, but have you released something like that. I know every person that uses this and would not like to let them down or otherwise block their work. Please be patient everything will be online in a few hours. A man has to eat and sleep after all. ❤️

**Comment by NikolaRHristov** [comment]
You can follow the issue here for more information - https://github.com/astro-community/astro-compress/issues/163

**Comment by NikolaRHristov** [comment]
@vcampitelli https://github.com/astro-community/astro-compress/issues/163#issuecomment-1670440767
